config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'static_pages/index'
  get 'static_pages/secret'
  devise_for :users
  get '/acceuil', to: 'event#acceuil'
  get '/event', to: 'event#event'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  
  def index
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def secret
  end

      before_action :authenticate_user!, only: [:secret]
  
  def after_create
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/event/acceuil.html.erb
<center><h1><i>Bienvenue sur le site</i></h1>
<h2>Voici la liste des événements :</h2>

app/views/event/event.html.erb
<center><h1><i>Crée ton événement</i></h1>

<form>

 <div class="form-floating col-5 m-3">
      <input type="last_name" class="form-control" id="floatingInput" placeholder="last_name">
      <label for="floatingInput">Ton nom et prénom</label>
    </div>

        <div class="form-floating col-5 m-3">
      <input type="last_name" class="form-control" id="floatingInput" placeholder="last_name">
      <label for="floatingInput">Nom de ton événemeent</label>
    </div>

        <div class="form-floating col-5 m-3">
      <input type="last_name" class="form-control" id="floatingInput" placeholder="last_name">
      <label for="floatingInput">Date de ton événement</label>
    </div>

    <div class="form-floating col-5 m-3">
      <input type="last_name" class="form-control" id="floatingInput" placeholder="last_name">
      <label for="floatingInput">Décris-nous ce qu'il va se passer</label>
    </div>
    <div class="checkbox mb-3">
    </div>
    <button class="wbtn btn-lg btn-primary col-3 m-3" type="submit">Ajoute-le</button>
  </form></center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event World</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<link rel="preconnect" href="https://fonts.googleapis.com"> 
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
<link href="https://fonts.googleapis.com/css2?family=Concert+One&display=swap" rel="stylesheet">
  </head>

  <body>

  <div class="container">
    <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="/" class="nav-link px-2 link-blue">EVENT WORLD</a></li>
        <li><a href="/acceuil" class="nav-link px-2 link-dark">Acceuil</a></li>
        <li><a href="/event" class="nav-link px-2 link-dark">Crée ton événement</a></li>

      </ul>
       <div class="col-md-3 text-end">
        
        <%= link_to "Inscription", new_user_registration_path, class: "btn btn-outline-primary me-2"%>
        <%= link_to "Connexion", new_user_session_path, class: "btn btn-outline-primary me-2"%>
      </div>

    </nav>
  </div>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1><center>Page d'acceuil</h1>
<p><center>ce projet me fait galerer !!</p>
<div class="jumbotron" ></div>
<ul>
  <% if user_signed_in? %>
    <li>
     <%= button_to( "Log Out", destroy_user_session_path,  method: :delete) %>
    </li>

    <li>
     Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>


  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

<%= link_to "Back", :back %>